---
title: "Visualization I"
author: "Sherry Zhang"
date: "2024-09-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

make first plot.

```{r}
ggplot(weather_df, aes(x=tmin, y=tmax))+
  geom_point()
```

```{r}
ggp_weather = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) 

ggp_weather + geom_point()

```

# Fancier scatterplot

```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax, color = name))+
  geom_point(alpha = 0.3, size = 0.8) +
  geom_smooth(se=FALSE)
```

Where you definine geom_point

```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax))+
  geom_point(aes(color=name), alpha = 0.3, size = 0.8) +
  geom_smooth(se=FALSE)
```

using faceting real quick

```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax, color=name))+
  geom_point(alpha = 0.3) +
  geom_smooth(se=FALSE)+
  facet_grid(. ~name)

```

more interesting scatter plot

```{r}
weather_df |> 
  ggplot(aes(x=date, y=tmax, color=name, size=prcp))+
  geom_point(alpha = 0.3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~name)
  
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmax_fahr = tmax *(9/5)+32,
    tmin_fahr = tmin *(9/5)+32,
  ) |> 
  ggplot(aes(x=tmin_fahr, y=tmax_fahr))+
  geom_point()+
  geom_smooth(method="lm", se = FALSE)
```

## small things 

```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax))+
  geom_point(aes(color=name), alpha = 0.3)+
  geom_smooth(se=FALSE)
```

```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax))+
  geom_hex()
```

```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax))+
  geom_point(color="blue")
```

## Univariate plots

```{r}
weather_df |> 
  ggplot(aes(x=tmin, fill = name))+
  geom_histogram(position = "dodge")
```

how to fix 

```{r}
weather_df |> 
  ggplot(aes(x=tmin, fill = name))+
  geom_histogram()+
  facet_grid(.~name)
```

density plot?

```{r}
weather_df |> 
  ggplot(aes(x=tmin, fill = name))+
  geom_density(alpha=.3)
```

```{r}
weather_df |> 
  ggplot(aes(x=name, y=tmin, fill=name))+
  geom_boxplot()
```

violin plot

```{r}
weather_df |> 
  ggplot(aes(x=name, y=tmin, fill = name))+
  geom_violin(alpha=.3)+
  stat_summary(fun = "median", color = "blue")
```

ridge plot

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

```{r}
weather_df |> 
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha=.3)
```

## Saving and embedding plots

```{r}
ggp_weather = 
  ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("ggp_weather.pdf", ggp_weather, width = 8, height = 5)
```

```{r, fig.width=8, fig.asp=.6}
ggp_weather = 
  ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 
```

